DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `Member`
(
    `USER_ID`    VARCHAR(20) PRIMARY KEY COMMENT '회원 아이디',
    `PASSWORD`   VARCHAR(20) NOT NULL COMMENT '비밀번호',
    `USER_NAME`  VARCHAR(20) NULL COMMENT '이름',
    `ROLE`   VARCHAR(20) NOT NULL COMMENT '역할',
    `TEL`   VARCHAR(20)  NULL COMMENT '전화번호',
    `CREATED_AT`  timestamp NOT NULL COMMENT '생성일자'
);

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE `PRODUCT`
(
    `PRODUCT_ID`    BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '상품번호',
    `CATEGORY`      VARCHAR(20) NULL COMMENT '상품 카테고리',
    `PRODUCT_NAME`   VARCHAR(20) NULL NULL COMMENT '상품명',
    `PRICE`   INT NOT NULL COMMENT '가격',
    `STOCK`   INT NOT NULL COMMENT '재고',
    `INFO`    TEXT NULL COMMENT '상품 정보',
    `PRODUCT_IMG` VARCHAR(30) NULL COMMENT '상품 이미지'

);

ALTER TABLE `PRODUCT`
MODIFY COLUMN `PRODUCT_NAME` VARCHAR(50) NULL COMMENT '상품명';

DROP TABLE IF EXISTS `CART`;

CREATE TABLE `CART`
(
    `CART_ID`    BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '장바구니 번호',
    `USER_ID`      VARCHAR(20) NOT NULL COMMENT '회원 아이디',
    CONSTRAINT `fk_user` FOREIGN KEY (`USER_ID`) REFERENCES `Member`(`USER_ID`)
);

DROP TABLE IF EXISTS `CART_DETAILS`;

CREATE TABLE `CART_DETAILS`
(
    `CART_DETAILS_ID`    INT AUTO_INCREMENT PRIMARY KEY COMMENT '장바구니 번호',
    `CART_ID`      BIGINT NOT NULL COMMENT '장바구니 아이디',
    `PRODUCT_ID`   BIGINT NULL NULL COMMENT '상품번호',
    `PRODUCT_CNT`   INT NOT NULL COMMENT '상품 수량',
    `CREATED_AT` timestamp   NOT NULL DEFAULT now() COMMENT '생성일자',
    CONSTRAINT `fk_cart` FOREIGN KEY (`CART_ID`) REFERENCES `CART`(`CART_ID`),
    CONSTRAINT `fk_product` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`)
);
